LRDOCS-10170 Remote Apps Overview Articles
JamesAGarcia/liferay-learn pull request #73
Opened 2022-02-22 07:12 UTC by JamesAGarcia

This PR includes three new articles, per [LRDOCS-10170](https://issues.liferay.com/browse/LRDOCS-10170): 
* [Remote Apps](https://github.com/JamesAGarcia/liferay-learn/blob/LRDOCS-10170/docs/dxp/latest/en/building-applications/remote-apps.md)
* [Understanding Remote App Types](https://github.com/JamesAGarcia/liferay-learn/blob/LRDOCS-10170/docs/dxp/latest/en/building-applications/remote-apps/understanding-remote-app-types.md)
* [Remote Apps UI Reference](https://github.com/JamesAGarcia/liferay-learn/blob/LRDOCS-10170/docs/dxp/latest/en/building-applications/remote-apps/remote-apps-ui-reference.md)

Please let me know if there's anything that should be corrected or included in these articles. I'd appreciate any input!
Also, I have several questions:

Q1) How is the client SDK provided for IFrame applications?
Q2) How exactly does the HTML Element Name name field work? Does it simply determine the name of the `<custom-element>` (e.g., `vanilla-counter`)?
Q3) Are there any requirements I should note when talking about how users host Custom Element code?
Q4) Should I bring up CORS when talking about IFrame applications?

2022-03-02 10:42 UTC, pablo-agulla commented
Sorry for not coming back to you earlier. Here are my comments:

Q1 - I think @dsanz can answer better
Q2 - IIRC yes, it's going to transformed into the HTML tag when embedding it in the portal
Q3 - I think there are no specific requirements for hosting the files, but reviewing this: https://github.com/JamesAGarcia/liferay-learn/blob/LRDOCS-10170/docs/dxp/latest/en/building-applications/remote-apps/creating-a-liferay-remote-app.md (which I'm not sure if it's part of this PR or not) I do have some comments:
 - create_remote_app.sh is a script we provide, but for sure not the only way to create remote apps. We should include and document links for how you can use React, Vue or Angular standard tooling to build them. (does the script does not support Angular?)
 - I think the mention for hosting the files in docs and media should be done as an example or even a workaround for how easy it is to do. It looks like it's the only way to host it. They could be storing the app in another private server, AWS, Azure, Google Cloud service, etc.
 Q4 - @dsanz can answer better

2022-03-31 18:50 UTC, dsanz requested changes
I've made some comments here and there about the files involved in this pull.

About the creating-a-liferay-remote-app.md, my main concern is that it describes just a specific way to create remote apps, by no means the only way. Similarly, the using-routes-with-remote-apps.md describes a particular technique to make use of a property to render a different file depending on that property's value, however, that is a very narrow/particular interpretation of the concept of "routing" single-page applications.

Those 2 tutorials may be read as "the right way (TM)" to do things, because we are not saying that what we describe there are just fast ways to get started. I think the value those tutorials provide is good, nevertheless, we should state and clarify that what they describe are just examples to achieve the desired result of creating remote apps.

I'd like to minimize the risk of defeating the agnostic nature of remote apps, which is one of its greatest contributions.

2022-03-31 18:50 UTC, dsanz commented on docs/dxp/latest/en/building-applications/remote-apps/understanding-remote-app-types.md
> +When the Remote App's widget is added to a Page, it's rendered as an `<iframe>` element using the [`_renderIFrame`](https://github.com/liferay/liferay-portal/blob/7bf2fe6b90af5f50a2fd3d0d77f1148fb71f
I'm not sure it's good idea to add code references here, as code placement (lines and class names) may change in the future. We should describe the high-level logic of the iframe apps render mechanism, which is much more unlikely to change.

2022-03-31 18:50 UTC, dsanz commented on docs/dxp/latest/en/building-applications/remote-apps/understanding-remote-app-types.md
> +The entry's widget then renders the application's mark up in a `<custom-element>` using the [`_renderCustomElement`](https://github.com/liferay/liferay-portal/blob/7bf2fe6b90af5f50a2fd3d0d77f1148fb71
Same considerations about pointing to specific lines of code. We may just explain this in the lines of:

Once custom element is registered in the page, widget renders the application markup by generating a tag with the provided HTML element name, which in turn executes the custom element logic defined by the application code. If the entry (or widget instance) includes properties, they are added to the generated custom element markup (`<custom-element (+props)/>`).

2022-03-31 18:50 UTC, dsanz commented on docs/dxp/latest/en/building-applications/remote-apps/understanding-remote-app-types.md
> +Once rendered, the application has full access the Liferay JS API and style classes. However, if you use Shadow DOM to isolate the DOM created within the `<custom-element>`, it won't receive any styl
We may add some extra details, like:

Once custom element is rendered, application is filly integrated in the page: it can make use of Liferay public JS API and reuse style classes already available in the host page. Note however that this is not mandatory. For example, if application markup is generated as [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM), styles defined by the app will be encapsulated within the custom element, not leaking outside it. Also, CSS selectors from the host page will not apply inside the component.

2022-04-05 00:32 UTC, closed without merging